refactor: move script into configmaps and other small tweaks

diff --git a/helm/selfservice-consumer/templates/configmap.yaml b/helm/selfservice-consumer/templates/configmap.yaml
--- a/helm/selfservice-consumer/templates/configmap.yaml
+++ b/helm/selfservice-consumer/templates/configmap.yaml
@@ -28,7 +28,7 @@ data:
 kind: "ConfigMap"
 apiVersion: "v1"
 metadata:
-  name: {{ printf "%s-wait-for-provisioning-api" (include "common.names.fullname" .) }}
+  name: {{ printf "%s-scripts" (include "common.names.fullname" .) }}
   namespace: {{ include "common.names.namespace" . | quote }}
   labels:
     {{- include "common.labels.standard" . | nindent 4 }}
@@ -39,5 +39,32 @@ metadata:
   annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
   {{- end }}
 data:
-{{ (.Files.Glob "wait-for-provisioning-api.sh").AsConfig | required "Missing wait-for-api.sh config file" | indent 2 }}
+  wait-for-provisioning-api.sh: |
+    set -uo pipefail
+
+    retry_interval=2
+    response_code=404
+    timeout_duration=120
+    end_time=$((SECONDS + timeout_duration))
+
+    while [ "$response_code" -ne 200 ]; do
+      if [ $SECONDS -ge $end_time ]; then
+        echo "Timeout reached. Exiting."
+        exit 1
+      fi
+
+      echo "Waiting for the Provisioning API to be available ..."
+      response_code=$(curl -s -o response.txt -w "%{http_code}" "${PROVISIONING_API_BASE_URL}/subscriptions/v1/subscriptions/${PROVISIONING_API_USERNAME}" -u "${PROVISIONING_API_USERNAME}":"${PROVISIONING_API_PASSWORD}")
+      if [ "${response_code}" -ne 200 ]; then
+        echo "Provisioning API is not reachable, status code: $response_code"
+        cat response.txt
+        sleep ${retry_interval}
+      else
+        echo "The Provisioning API is reachable"
+        exit 0
+      fi
+    done
+
+    echo "Permanent error ocurred. Exiting."
+    exit 1
 ...
